name: attendance_appp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.0.0
  camera: ^0.10.0
  path_provider: ^2.0.11
  path: ^1.8.2
  image: ^3.2.0
  cupertino_icons: ^1.0.5
  google_maps_flutter: ^2.12.1
  geolocator: ^13.0.4
  custom_info_window: ^1.0.1
  shared_preferences: ^2.5.3
  http: ^1.3.0
  latlong2: ^0.9.1
  flutter_map: ^8.1.1
  flutter_map_location_marker: ^10.0.2
  location: ^8.0.0
  flutter_polyline_points: ^2.1.0
  google_mlkit_face_detection: ^0.13.1
  supabase_flutter: ^2.9.1
  dartz: ^0.10.1
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  month_picker_dialog: ^6.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/